from odoo import models
from odoo.addons.account.models.chart_template import template

class AccountChartTemplate(models.AbstractModel):
    _inherit = 'account.chart.template'

    @template('pa_simplificat')
    def _get_pa_simplificat_template_data(self):
        return {
            'name': 'Simplifica T (Panamá)',
            'visible': True,
            'property_account_receivable_id': 'pa_account_120_01',
            'property_account_payable_id': 'pa_account_220_02',
            'property_account_income_categ_id': 'pa_account_400_01',
            'property_account_expense_categ_id': 'pa_account_500_02',
            'code_digits': 0,
        }

    @template('pa_simplificat', 'res.company')
    def _get_pa_simplificat_res_company(self):
        return {
            self.env.company.id: {
                'account_fiscal_country_id': 'base.pa',
                'bank_account_code_prefix': '100.50',
                'cash_account_code_prefix': '100.60',
                'transfer_account_code_prefix': '100.99',
                'account_default_pos_receivable_account_id': 'pa_account_120_01',
                'income_currency_exchange_account_id': 'pa_account_601_01',
                'expense_currency_exchange_account_id': 'pa_account_601_01',
                'account_journal_suspense_account_id': 'pa_account_100', # Usually 100.99 but fallback to 100
                'account_journal_early_pay_discount_loss_account_id': 'pa_account_500_05',
                'account_journal_early_pay_discount_gain_account_id': 'pa_account_400_07',
                'default_cash_difference_income_account_id': 'pa_account_400_07',
                'default_cash_difference_expense_account_id': 'pa_account_601_33',
            }
        }

    @template('pa_simplificat', 'account.account')
    def _get_pa_simplificat_account_account(self):
        return {
            'pa_account_100': {'name': 'ACTIVO', 'code': '100', 'account_type': 'asset_cash'},
            'pa_account_100_02': {'name': 'CAJA MENUDA', 'code': '100.02', 'account_type': 'asset_cash'},
            'pa_account_100_03': {'name': 'BANCO GENERAL CTA. CORRIENTE', 'code': '100.03', 'account_type': 'asset_cash'},
            'pa_account_100_04': {'name': 'ST. GEORGES BANK', 'code': '100.04', 'account_type': 'asset_cash'},
            'pa_account_100_05': {'name': 'BAC CREDOMATIC', 'code': '100.05', 'account_type': 'asset_cash'},
            'pa_account_100_13': {'name': 'BANCO GENERAL CTA. DE AHORRO', 'code': '100.13', 'account_type': 'asset_cash'},
            'pa_account_120_01': {'name': 'CUENTAS POR COBRAR CLIENTE', 'code': '120.01', 'account_type': 'asset_receivable'},
            'pa_account_120_02': {'name': 'OTRAS CUENTAS POR COBRAR', 'code': '120.02', 'account_type': 'asset_current'},
            'pa_account_120_03': {'name': 'PROV.CTAS. INCOBRABLES', 'code': '120.03', 'account_type': 'asset_receivable'},
            'pa_account_120_1': {'name': 'CUENTAS POR COBRAR EMPLEADO', 'code': '120.1', 'account_type': 'asset_receivable'},
            'pa_account_120_14': {'name': 'SEGURO PAGADO POR ANT.', 'code': '120.14', 'account_type': 'asset_current'},
            'pa_account_120_15': {'name': 'GASTO PAGADO POR ANT.', 'code': '120.15', 'account_type': 'asset_current'},
            'pa_account_120_17': {'name': 'IMPUESTO COMPLEMENTARIO', 'code': '120.17', 'account_type': 'asset_current'},
            'pa_account_120_18': {'name': 'IMP.PAGADO POR ADELANTADO', 'code': '120.18', 'account_type': 'asset_current'},
            'pa_account_130': {'name': 'INVENTARIO', 'code': '130', 'account_type': 'asset_current'},
            'pa_account_140_01': {'name': 'EQUIPOS DE OFICINA', 'code': '140.01', 'account_type': 'asset_fixed'},
            'pa_account_140_02': {'name': 'MOBILIARIO Y ENSERES', 'code': '140.02', 'account_type': 'asset_fixed'},
            'pa_account_140_03': {'name': 'EQUIPOS DE COMPUTO', 'code': '140.03', 'account_type': 'asset_fixed'},
            'pa_account_140_04': {'name': 'MEJORAS', 'code': '140.04', 'account_type': 'asset_fixed'},
            'pa_account_140_05': {'name': 'EQUIPO DE AIRE ACONDICIONADO', 'code': '140.05', 'account_type': 'asset_fixed'},
            'pa_account_140_06': {'name': 'EQUIPO RODANTE', 'code': '140.06', 'account_type': 'asset_fixed'},
            'pa_account_140_08': {'name': 'EQUIPO DE VIGILANCIA', 'code': '140.08', 'account_type': 'asset_fixed'},
            'pa_account_140_09': {'name': 'SOFTWARE', 'code': '140.09', 'account_type': 'asset_fixed'},
            'pa_account_141_01': {'name': 'DEP. ACUM. EQUIPO DE OFICINA', 'code': '141.01', 'account_type': 'asset_fixed'},
            'pa_account_141_02': {'name': 'DEP. ACUM. MOBILIARIO', 'code': '141.02', 'account_type': 'asset_fixed'},
            'pa_account_141_03': {'name': 'DEP. ACUM. EQUIPOS DE COMPUTO', 'code': '141.03', 'account_type': 'asset_fixed'},
            'pa_account_141_04': {'name': 'AMORTIZACION DE MEJORAS', 'code': '141.04', 'account_type': 'asset_fixed'},
            'pa_account_141_05': {'name': 'DEP. ACUM. AIRE ACONDICIONADO', 'code': '141.05', 'account_type': 'asset_fixed'},
            'pa_account_141_06': {'name': 'DEP. ACUM. EQUIPO RODANTE', 'code': '141.06', 'account_type': 'asset_fixed'},
            'pa_account_141_08': {'name': 'DEP.ACUM.EQUIPO DE VIGILANCIA', 'code': '141.08', 'account_type': 'asset_fixed'},
            'pa_account_141_09': {'name': 'DEP. ACUM. SOFTWARE', 'code': '141.09', 'account_type': 'asset_fixed'},
            'pa_account_150_01': {'name': 'IS RENTA ESTIMADA', 'code': '150.01', 'account_type': 'asset_current'},
            'pa_account_150_02': {'name': 'DEPOSITO DE GARANTIA', 'code': '150.02', 'account_type': 'asset_current'},
            'pa_account_160_01': {'name': 'CTA. POR COBRAR ACCIONISTA', 'code': '160.01', 'account_type': 'asset_receivable'},
            'pa_account_190_01': {'name': 'OTROS  ACTIVOS', 'code': '190.01', 'account_type': 'asset_current'},
            'pa_account_200': {'name': 'PASIVOS', 'code': '200', 'account_type': 'liability_payable'},
            'pa_account_220_01': {'name': 'IMPUESTOS POR PAGAR', 'code': '220.01', 'account_type': 'liability_payable'},
            'pa_account_220_02': {'name': 'CTAS. POR PAGAR PROVEEDORES', 'code': '220.02', 'account_type': 'liability_payable'},
            'pa_account_220_02_01': {'name': 'CTAS. POR PAGAR MASTER CARD', 'code': '220.02.01', 'account_type': 'liability_payable'},
            'pa_account_220_02_04': {'name': 'CTAS. POR PAGAR VISA PYME', 'code': '220.02.04', 'account_type': 'liability_payable'},
            'pa_account_220_02_06': {'name': 'SEGUROS POR PAGAR', 'code': '220.02.06', 'account_type': 'liability_payable'},
            'pa_account_220_03': {'name': 'CTAS. POR PAGAR OTROS', 'code': '220.03', 'account_type': 'liability_payable'},
            'pa_account_220_04': {'name': 'SEGURO SOCIAL POR PAGAR', 'code': '220.04', 'account_type': 'liability_payable'},
            'pa_account_220_04_04': {'name': 'PROV. XIII MES', 'code': '220.04.04', 'account_type': 'liability_payable'},
            'pa_account_220_04_05': {'name': 'PROV. DE VACACIONES POR PAGAR', 'code': '220.04.05', 'account_type': 'liability_payable'},
            'pa_account_220_04_06': {'name': 'PROV DE PRIMA POR PAGAR', 'code': '220.04.06', 'account_type': 'liability_payable'},
            'pa_account_220_04_07': {'name': 'PROV DE INDEMNIZACION', 'code': '220.04.07', 'account_type': 'liability_payable'},
            'pa_account_220_04_08': {'name': 'DESCUENTO EMPLEADO', 'code': '220.04.08', 'account_type': 'liability_payable'},
            'pa_account_220_04_09': {'name': 'RETENCION EMPLEADO ISR', 'code': '220.04.09', 'account_type': 'liability_payable'},
            'pa_account_220_05': {'name': 'SALARIOS POR PAGAR', 'code': '220.05', 'account_type': 'liability_payable'},
            'pa_account_220_06': {'name': 'PRESTAMOS POR PAGAR', 'code': '220.06', 'account_type': 'liability_non_current'},
            'pa_account_230_01': {'name': 'ITBMS POR PAGAR', 'code': '230.01', 'account_type': 'liability_payable'},
            'pa_account_290': {'name': 'OTROS PASIVOS', 'code': '290', 'account_type': 'liability_current'},
            'pa_account_290_01': {'name': 'CUENTAS POR PAGAR - ACCIONISTA', 'code': '290.01', 'account_type': 'liability_current'},
            'pa_account_300': {'name': 'CAPITAL', 'code': '300', 'account_type': 'equity'},
            'pa_account_300_02': {'name': 'SUPERAVIT O DEFICIT ACUMULADO', 'code': '300.02', 'account_type': 'equity'},
            'pa_account_300_03': {'name': 'GANANCIA O PERDIDA DEL PERIODO', 'code': '300.03', 'account_type': 'equity'},
            'pa_account_300_04': {'name': 'CAPITAL ADICIONAL PAGADO', 'code': '300.04', 'account_type': 'equity'},
            'pa_account_400': {'name': 'INGRESOS', 'code': '400', 'account_type': 'income'},
            'pa_account_400_01': {'name': 'VENTAS', 'code': '400.01', 'account_type': 'income'},
            'pa_account_400_02': {'name': 'VENTAS EXENTAS', 'code': '400.02', 'account_type': 'income'},
            'pa_account_400_03': {'name': 'DEVOLUCION DE VENTAS', 'code': '400.03', 'account_type': 'income'},
            'pa_account_400_04': {'name': 'DESCUENTO EN VENTAS', 'code': '400.04', 'account_type': 'income'},
            'pa_account_400_05': {'name': 'SERVICIO DE ENTREGA', 'code': '400.05', 'account_type': 'income'},
            'pa_account_400_07': {'name': 'OTROS INGRESOS', 'code': '400.07', 'account_type': 'income'},
            'pa_account_400_1': {'name': 'INTERESES GANADOS-CTA.AHORRO', 'code': '400.1', 'account_type': 'income'},
            'pa_account_400_15': {'name': 'GAN/PERD VENTA ACTIVO', 'code': '400.15', 'account_type': 'income'},
            'pa_account_500_01': {'name': 'COMPRAS', 'code': '500.01', 'account_type': 'expense_direct_cost'},
            'pa_account_500_02': {'name': 'COSTO MERC. VENDIDA-GRAVADA', 'code': '500.02', 'account_type': 'expense_direct_cost'},
            'pa_account_500_04': {'name': 'DESCUENTOS EN COMPRAS', 'code': '500.04', 'account_type': 'expense_direct_cost'},
            'pa_account_500_05': {'name': 'DESCUENTO POR PRONTO PAGO', 'code': '500.05', 'account_type': 'expense_direct_cost'},
            'pa_account_500_06': {'name': 'COSTO PRODUCTO DEFECTUOSO', 'code': '500.06', 'account_type': 'expense_direct_cost'},
            'pa_account_500_07': {'name': 'MUESTRAS', 'code': '500.07', 'account_type': 'expense_direct_cost'},
            'pa_account_500_08': {'name': 'OTROS COSTOS', 'code': '500.08', 'account_type': 'expense_direct_cost'},
            'pa_account_500_1': {'name': 'COSTO NO DEDUCIBLE', 'code': '500.1', 'account_type': 'expense_direct_cost'},
            'pa_account_600': {'name': 'GASTOS', 'code': '600', 'account_type': 'expense'},
            'pa_account_601_01': {'name': 'GASTOS GENERALES', 'code': '601.01', 'account_type': 'expense'},
            'pa_account_601_02': {'name': 'SALARIOS', 'code': '601.02', 'account_type': 'expense'},
            'pa_account_601_02_01': {'name': 'XIII MES', 'code': '601.02.01', 'account_type': 'expense'},
            'pa_account_601_02_02': {'name': 'VACACIONES', 'code': '601.02.02', 'account_type': 'expense'},
            'pa_account_601_02_03': {'name': 'PRIMA DE ANTIGUEDAD', 'code': '601.02.03', 'account_type': 'expense'},
            'pa_account_601_02_04': {'name': 'INDEMNIZACION', 'code': '601.02.04', 'account_type': 'expense'},
            'pa_account_601_02_05': {'name': 'S.S. PATRONAL', 'code': '601.02.05', 'account_type': 'expense'},
            'pa_account_601_02_06': {'name': 'S.E. PATRONAL', 'code': '601.02.06', 'account_type': 'expense'},
            'pa_account_601_02_07': {'name': 'RIESGO PROFESIONAL', 'code': '601.02.07', 'account_type': 'expense'},
            'pa_account_601_02_09': {'name': 'VALE ALIMENTICIO', 'code': '601.02.09', 'account_type': 'expense'},
            'pa_account_601_02_10': {'name': 'UNIFORMES', 'code': '601.02.10', 'account_type': 'expense'},
            'pa_account_601_02_11': {'name': 'COMISIONES', 'code': '601.02.11', 'account_type': 'expense'},
            'pa_account_601_02_13': {'name': 'BONO', 'code': '601.02.13', 'account_type': 'expense'},
            'pa_account_601_03': {'name': 'ALQUILER', 'code': '601.03', 'account_type': 'expense'},
            'pa_account_601_04': {'name': 'SEGUROS', 'code': '601.04', 'account_type': 'expense'},
            'pa_account_601_04_01': {'name': 'MAPFRE PANAMA', 'code': '601.04.01', 'account_type': 'expense'},
            'pa_account_601_05': {'name': 'UTILES DE ASEO Y LIMPIEZA', 'code': '601.05', 'account_type': 'expense'},
            'pa_account_601_06': {'name': 'GASTO DE CAFETERIA', 'code': '601.06', 'account_type': 'expense'},
            'pa_account_601_07': {'name': 'PAPELERIA Y UTILES DE OFICINA', 'code': '601.07', 'account_type': 'expense'},
            'pa_account_601_09': {'name': 'GASTOS DE OFICINA', 'code': '601.09', 'account_type': 'expense'},
            'pa_account_601_1': {'name': 'GASTO DE SEGURIDAD', 'code': '601.1', 'account_type': 'expense'},
            'pa_account_601_11': {'name': 'ELECTRICIDAD', 'code': '601.11', 'account_type': 'expense'},
            'pa_account_601_12': {'name': 'TELEFONO, FAX E INTERNET', 'code': '601.12', 'account_type': 'expense'},
            'pa_account_601_14_02': {'name': 'IMPUESTO MUNICIPAL', 'code': '601.14.02', 'account_type': 'expense'},
            'pa_account_601_14_02_01': {'name': 'MULTA MUNICIPAL', 'code': '601.14.02.01', 'account_type': 'expense'},
            'pa_account_601_14_03': {'name': 'TASA UNICA', 'code': '601.14.03', 'account_type': 'expense'},
            'pa_account_601_14_04': {'name': 'ITBMS', 'code': '601.14.04', 'account_type': 'expense'},
            'pa_account_601_14_07': {'name': 'IMPUESTOS', 'code': '601.14.07', 'account_type': 'expense'},
            'pa_account_601_14_08': {'name': 'AMIR (DIR GRAL DE INGRESOS)', 'code': '601.14.08', 'account_type': 'expense'},
            'pa_account_601_14_11': {'name': 'IMPUESTO COMPLEMENTARIO', 'code': '601.14.11', 'account_type': 'expense'},
            'pa_account_601_14_12': {'name': 'AVISO DE OPERACION', 'code': '601.14.12', 'account_type': 'expense'},
            'pa_account_601_15_01': {'name': 'REP. Y MANTENIMIENTO DE AUTO', 'code': '601.15.01', 'account_type': 'expense'},
            'pa_account_601_16': {'name': 'DEPRECIACIONES Y AMORTIZACIONE', 'code': '601.16', 'account_type': 'expense'},
            'pa_account_601_16_01': {'name': 'DEP. EQUIPOS DE OFICINA', 'code': '601.16.01', 'account_type': 'expense'},
            'pa_account_601_16_02': {'name': 'DEP. MOBILIARIOS Y ENSERES', 'code': '601.16.02', 'account_type': 'expense'},
            'pa_account_601_16_03': {'name': 'DEP. EQUIPOS DE COMPUTO', 'code': '601.16.03', 'account_type': 'expense'},
            'pa_account_601_16_04': {'name': 'AMORTIZACIONES', 'code': '601.16.04', 'account_type': 'expense'},
            'pa_account_601_16_05': {'name': 'DEPRECIACION DE EQUIPO RODANTE', 'code': '601.16.05', 'account_type': 'expense'},
            'pa_account_601_16_06': {'name': 'DEPRECIACION DE AIRES ACONDIC.', 'code': '601.16.06', 'account_type': 'expense'},
            'pa_account_601_17': {'name': 'GASTOS DE INTERESES', 'code': '601.17', 'account_type': 'expense'},
            'pa_account_601_18': {'name': 'CARGOS BANCARIOS', 'code': '601.18', 'account_type': 'expense'},
            'pa_account_601_20_01': {'name': 'FLETE Y ACARREOS', 'code': '601.20.01', 'account_type': 'expense'},
            'pa_account_601_20_02': {'name': 'MENSAJERIA', 'code': '601.20.02', 'account_type': 'expense'},
            'pa_account_601_20_03': {'name': 'ENTREGA', 'code': '601.20.03', 'account_type': 'expense'},
            'pa_account_601_21': {'name': 'CURSOS Y SEMINARIOS', 'code': '601.21', 'account_type': 'expense'},
            'pa_account_601_22': {'name': 'VIAJES Y VIATICOS', 'code': '601.22', 'account_type': 'expense'},
            'pa_account_601_23': {'name': 'REPARACION Y MANTENIMIENTO', 'code': '601.23', 'account_type': 'expense'},
            'pa_account_601_3': {'name': 'HONORARIOS Y SER PROFESIONALES', 'code': '601.3', 'account_type': 'expense'},
            'pa_account_601_30_02': {'name': 'GASTOS  LEGALES', 'code': '601.30.02', 'account_type': 'expense'},
            'pa_account_601_32': {'name': 'PUBLICIDAD', 'code': '601.32', 'account_type': 'expense'},
            'pa_account_601_33': {'name': 'OTROS GASTOS', 'code': '601.33', 'account_type': 'expense'},
            'pa_account_601_39_08': {'name': 'PEAJES Y ESTACIONAMIENTOS', 'code': '601.39.08', 'account_type': 'expense'},
            'pa_account_601_40_02': {'name': 'COMBUSTIBLE Y LUBRICANTES', 'code': '601.40.02', 'account_type': 'expense'},
            'pa_account_601_41_01': {'name': 'MULTAS Y RECARGOS', 'code': '601.41.01', 'account_type': 'expense'},
            'pa_account_601_41_02': {'name': 'GASTOS NO DEDUCIBLES', 'code': '601.41.02', 'account_type': 'expense'},
            'pa_account_601_42': {'name': 'ATENCION AL CLIENTE', 'code': '601.42', 'account_type': 'expense'},
            'pa_account_601_43': {'name': 'ATENCION A EMPLEADO', 'code': '601.43', 'account_type': 'expense'},

        }
